language: c

sudo: required

git:
  depth: 1

services:
  - docker

notifications:
  email: change

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    - make push_all
  on:
    branch: master
