language: c

sudo: required

git:
  depth: 1

services:
  - docker

notifications:
  email: change

script:
  - make build_all

after_success:
  - docker --version  # document the version travis is using
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make push_all
